services:
  backend:
    build: ./main/
    restart: always
    ports:
      - "9001:9001"
    command: ['uv', 'run', './backend/rest.py']

  prefect-server:
    build: ./main/
    restart: always
    ports:
      - "4200:4200"
    command: ["sh", "./start_prefect.sh"]
    depends_on:
      - backend

  orchestration:
    build: ./main/    
    restart: always
    ports:
      - "3600:3600"
    command: ["sh", "./start_workers.sh"]
    depends_on: 
      - backend
      - prefect-server  